### ISSUE TITLE
Add `usePreferredColorScheme` hook

### ISSUE THREAD

**Issue by kripod** [kripod/standard-hooks#10]
## Motivation

Dark mode is getting increasingly popular. Developers may want to track the color scheme preference of users.

## Basic example

```js
const preferredColorScheme = usePreferredColorScheme();
```

## Details

- Depends on `useMedia` (#9)

**Comment by cmoog** [comment]
the PR above implements this hook ^ #12

**Comment by kripod** [comment]
@cmoog Thanks for your work! Unfortunately, I'm still not sure whether this hook should be generic or specialized for dark mode. If the latter approach gets used, then a simplistic approach could be chosen if the user has `no-preference` over the color scheme:

```js
const isDarkModeEnabled = useDarkMode(true /* default value if there is no preference */);
```

On the other hand, there might be more color scheme additions in the future, and the name `useDarkMode` has no hint about it being only a preference retrieval hook.

**Comment by cmoog** [comment]
@kripod I'm thinking it's best to keep it generic and leave it to the consumer to resolve the value to a boolean. For example, `isDarkMode` can be trivially implemented by the consumer as follows

```jsx
const isDarkMode = usePreferredColorScheme() === 'dark';
```

**Comment by kripod** [comment]
@cmoog Thanks for your work once again! If you decide to send a pull request again, [please](https://github.com/kripod/standard-hooks/blob/master/CONTRIBUTING.md#workflow) assign yourself to the corresponding issues and use [magic keywords](https://help.github.com/en/articles/closing-issues-using-keywords) to auto-close the issue for which your pull request was created.
