### ISSUE TITLE
What is the difference between this library and react-use?

### ISSUE THREAD

**Issue by testarossaaaaa** [kripod/standard-hooks#79]

**Comment by kripod** [comment]
Thank you for the question! While [react-use](https://github.com/streamich/react-use) offers a lot of different hooks, it relies on runtime dependencies and often has inefficient implementations.

**This project vs. react-use:**

- [`useDeviceMotion`](https://github.com/kripod/standard-hooks/blob/4b6b152627ce9a79cf2cd54dfc29dee71bb8a972/src/useDeviceMotion.ts) vs. [`useMotion`](https://github.com/streamich/react-use/blob/706f6607817c336a9324ea3fbee87661379bc909/src/useMotion.ts)
- [`useDeviceOrientation`](https://github.com/kripod/standard-hooks/blob/4b6b152627ce9a79cf2cd54dfc29dee71bb8a972/src/useDeviceOrientation.ts) vs. [`useOrientation`](https://github.com/streamich/react-use/blob/706f6607817c336a9324ea3fbee87661379bc909/src/useOrientation.ts), the latter using a [deprecated API](https://developer.mozilla.org/en-US/docs/Web/API/Window/orientationchange_event)
- [`useDocumentReadiness`](https://github.com/kripod/standard-hooks/blob/4b6b152627ce9a79cf2cd54dfc29dee71bb8a972/src/useDocumentReadiness.ts) has no alternative yet
- [`useDocumentVisibility`](https://github.com/kripod/standard-hooks/blob/4b6b152627ce9a79cf2cd54dfc29dee71bb8a972/src/useDocumentVisibility.ts) has no alternative yet
- [`useEventListener`](https://github.com/kripod/standard-hooks/blob/4b6b152627ce9a79cf2cd54dfc29dee71bb8a972/src/useEventListener.ts) vs. [`useEvent`](https://github.com/streamich/react-use/blob/706f6607817c336a9324ea3fbee87661379bc909/src/useEvent.ts), the latter re-subscribing to events when the callback changes
- [`useGeolocation`](https://github.com/kripod/standard-hooks/blob/4b6b152627ce9a79cf2cd54dfc29dee71bb8a972/src/useGeolocation.ts) vs. [`useGeolocation`](https://github.com/streamich/react-use/blob/706f6607817c336a9324ea3fbee87661379bc909/src/useGeolocation.ts), the latter having a lot of boilerplate and two functions unnecessarily re-declared during every render (`onEvent`, `onEventError`)
- [`useMedia`](https://github.com/kripod/standard-hooks/blob/4b6b152627ce9a79cf2cd54dfc29dee71bb8a972/src/useMedia.ts) vs. [`useMedia`](https://github.com/streamich/react-use/blob/706f6607817c336a9324ea3fbee87661379bc909/src/useMedia.ts), the latter using a [deprecated API](https://drafts.csswg.org/cssom-view/#dom-mediaquerylist-addlistener)
- [`useMouseCoords`](https://github.com/kripod/standard-hooks/blob/4b6b152627ce9a79cf2cd54dfc29dee71bb8a972/src/useMouseCoords.ts) vs. [`useMouse`](https://github.com/streamich/react-use/blob/706f6607817c336a9324ea3fbee87661379bc909/src/useMouse.ts), the former using a simple tuple as return value and no unnecessary RAF boilerplate
- [`useNetworkAvailability`](https://github.com/kripod/standard-hooks/blob/4b6b152627ce9a79cf2cd54dfc29dee71bb8a972/src/useNetworkAvailability.ts)/[`useNetworkInformation`](https://github.com/kripod/standard-hooks/blob/4b6b152627ce9a79cf2cd54dfc29dee71bb8a972/src/useNetworkInformation.ts) vs. [`useNetwork`](https://github.com/streamich/react-use/blob/706f6607817c336a9324ea3fbee87661379bc909/src/useNetwork.ts)
- [`usePreferredColorScheme`](https://github.com/kripod/standard-hooks/blob/4b6b152627ce9a79cf2cd54dfc29dee71bb8a972/src/usePreferredColorScheme.ts) has no alternative yet
- [`usePreferredLanguages`](https://github.com/kripod/standard-hooks/blob/4b6b152627ce9a79cf2cd54dfc29dee71bb8a972/src/usePreferredLanguages.ts) has no alternative yet
- [`useStorage`](https://github.com/kripod/standard-hooks/blob/4b6b152627ce9a79cf2cd54dfc29dee71bb8a972/src/useStorage.ts) vs. [`useLocalStorage`](https://github.com/streamich/react-use/blob/706f6607817c336a9324ea3fbee87661379bc909/src/useLocalStorage.ts), the former offering error handling and backwards compatibility for past stored non-serialized values
- [`useTimeline`](https://github.com/kripod/standard-hooks/blob/4b6b152627ce9a79cf2cd54dfc29dee71bb8a972/src/useTimeline.ts) has no alternative yet
- [`useUndoable`](https://github.com/kripod/standard-hooks/blob/4b6b152627ce9a79cf2cd54dfc29dee71bb8a972/src/useUndoable.ts) has no alternative yet
- [`useViewportScale`](https://github.com/kripod/standard-hooks/blob/4b6b152627ce9a79cf2cd54dfc29dee71bb8a972/src/useViewportScale.ts), [`useViewportScrollCoords`](https://github.com/kripod/standard-hooks/blob/4b6b152627ce9a79cf2cd54dfc29dee71bb8a972/src/useViewportScrollCoords.ts) and [`useViewportSize`](https://github.com/kripod/standard-hooks/blob/4b6b152627ce9a79cf2cd54dfc29dee71bb8a972/src/useViewportSize.ts) have no alternatives yet
- [`useWindowScrollCoords`](https://github.com/kripod/standard-hooks/blob/4b6b152627ce9a79cf2cd54dfc29dee71bb8a972/src/useWindowScrollCoords.ts) vs. [`useWindowScroll`](https://github.com/streamich/react-use/blob/706f6607817c336a9324ea3fbee87661379bc909/src/useWindowScroll.ts), the former using a simple tuple as return value and no unnecessary RAF boilerplate
- [`useWindowSize`](https://github.com/kripod/standard-hooks/blob/4b6b152627ce9a79cf2cd54dfc29dee71bb8a972/src/useWindowSize.ts) vs. [`useWindowSize`](https://github.com/streamich/react-use/blob/706f6607817c336a9324ea3fbee87661379bc909/src/useWindowSize.ts), the former using a simple tuple as return value and no unnecessary RAF boilerplate

Nearly a month ago, I have [answered](https://www.reddit.com/r/reactjs/comments/d4mnvk/announcing_standardhooks_for_convenient_web_api/f0f7o3s/) a question on Reddit, mentioning what makes this library stand out amongst its competitors. Hopefully, the ongoing development efforts will result in a more diverse set of well-tested building blocks, reusable through a wide variety of projects.

If you have anything to add, please feel free to reopen this discussion!
