### ISSUE TITLE
Why not use `window.matchMedia` for a `useMedia` hook?

### ISSUE THREAD

**Issue by cmoog** [kripod/standard-hooks#8]
I'm wondering if `useMedia` could be a simpler API than `useWindowSize` and `useDeviceOrientation`.

Example usage
```jsx
const isWidescreen = useMedia('(min-width: 500px)');
```

Any thoughts?

**Comment by kripod** [comment]
Thank you for the idea! I was thinking about adding 'useMedia' as a separate hook. Please continue this discussion in #9.
