### ISSUE TITLE
Add husky for format and lint before commit

### ISSUE THREAD

**Issue by Jfelix61** [kripod/standard-hooks#80]
## Motivation

Since the contributor has to run ```yarn format``` and ```yarn lint``` before committing, this can result in someone committing without running both of these.  We could add husky to handle this for us automatically and ensure commits are correct in terms of format and lint before code review in PR.

## Basic example

Just by ```git commit -m "MESSAGE"``` the code would be linted and formatted.

**Comment by kripod** [comment]
Thanks for the suggestion! Would you like to implement this, similar to how it's done in [gatsby-starter-strict](https://github.com/kripod/gatsby-starter-strict)?

Please follow [this](https://github.com/kripod/gatsby-starter-strict/pull/647/files), [this](https://github.com/kripod/gatsby-starter-strict/commit/bb5acce0ad603e3b76ca6857b96b856259e10f66), [this](https://github.com/kripod/gatsby-starter-strict/commit/0012b2860423cbf077b066f661be987f3c8a7a7c) and then [this](https://github.com/kripod/gatsby-starter-strict/commit/f229d069b86275b6ee13480da339287679832419) set of changes.
