### ISSUE TITLE
Add `useMedia` hook

### ISSUE THREAD

**Issue by kripod** [kripod/standard-hooks#9]
## Motivation

Track whether a document matches the given media query. This may also be used for a `usePreferredColorScheme` (or `useDarkMode`) hook.

## Basic example

```js
const isDesktop = useMedia('(min-width: 1024px)');
```

## Details

- [Window.matchMedia()](https://developer.mozilla.org/docs/Web/API/Window/matchMedia)

**Comment by cmoog** [comment]
The PR above implements this enhancement #11

**Comment by kripod** [comment]
Implemented by #11
